// Shared by the existing UI dictionary and API responses; data language is separate.
export const audienceStyleStrings = {
  "audienceStyle.title": { zh: "受众与风格", en: "Audience/Style" },
  "audienceStyle.create": { zh: "新建标签", en: "New Tag" },
  "audienceStyle.id": { zh: "ID", en: "ID" },
  "audienceStyle.idHint": { zh: "唯一且稳定的标识，保存后不可修改。", en: "A unique, stable identifier. It cannot change after saving." },
  "audienceStyle.name": { zh: "名称", en: "Name" },
  "audienceStyle.kind": { zh: "类型", en: "Type" },
  "audienceStyle.audience": { zh: "受众", en: "Audience" },
  "audienceStyle.style": { zh: "风格", en: "Style" },
  "audienceStyle.all": { zh: "全部", en: "All" },
  "audienceStyle.filter": { zh: "按类型筛选", en: "Filter by type" },
  "audienceStyle.language": { zh: "内容语言", en: "Content Language" },
  "audienceStyle.zh": { zh: "中文", en: "Chinese" },
  "audienceStyle.en": { zh: "英文", en: "English" },
  "audienceStyle.description": { zh: "简短说明", en: "Description" },
  "audienceStyle.readerExperience": { zh: "目标读者与阅读体验", en: "Readers and Reading Experience" },
  "audienceStyle.narrativeStyle": { zh: "叙事风格", en: "Narrative Style" },
  "audienceStyle.relationshipAndElements": { zh: "人物关系与常见元素", en: "Relationships and Common Elements" },
  "audienceStyle.avoidElements": { zh: "避免或限制元素", en: "Elements to Avoid or Limit" },
  "audienceStyle.creativeBrief": { zh: "创作提示（Markdown）", en: "Creative Brief (Markdown)" },
  "audienceStyle.briefHint": { zh: "可直接编辑 Markdown，作为给写作 Agent 的轻量创作提示。", en: "Edit Markdown directly as a lightweight creative brief for the writing agent." },
  "audienceStyle.addItem": { zh: "添加条目", en: "Add Item" },
  "audienceStyle.removeItem": { zh: "删除条目", en: "Remove Item" },
  "audienceStyle.empty": { zh: "暂无受众与风格标签，创建第一个标签开始。", en: "No audience/style tags yet. Create your first tag to get started." },
  "audienceStyle.noMatches": { zh: "没有符合筛选条件的标签。", en: "No tags match this filter." },
  "audienceStyle.noContent": { zh: "未填写", en: "Not provided" },
  "audienceStyle.selectHint": { zh: "选择标签查看详情。", en: "Select a tag to view its details." },
  "audienceStyle.back": { zh: "返回列表", en: "Back to List" },
  "audienceStyle.viewDetail": { zh: "查看详情", en: "View Details" },
  "audienceStyle.copy": { zh: "复制到项目", en: "Copy to Project" },
  "audienceStyle.copyHint": { zh: "复制到当前项目并保留独立快照，不改变题材。", en: "Copy an independent snapshot to the current project while preserving its genre." },
  "audienceStyle.copied": { zh: "标签已复制到当前项目。", en: "Tag copied to the current project." },
  "audienceStyle.alreadyCopied": { zh: "项目已有此标签，未重复添加。", en: "This tag is already in the project; no duplicate was added." },
  "audienceStyle.saved": { zh: "标签已保存。", en: "Tag saved." },
  "audienceStyle.deleted": { zh: "标签已删除。", en: "Tag deleted." },
  "audienceStyle.deleteTitle": { zh: "删除标签", en: "Delete Tag" },
  "audienceStyle.deleteConfirm": { zh: "确认删除标签「{name}」？已复制到项目的快照会保留。", en: "Delete tag “{name}”? Snapshots already copied to the project will be kept." },
  "audienceStyle.invalidId": { zh: "请输入有效 ID，不能包含路径分隔符或连续两个点。", en: "Enter a valid ID without path separators or consecutive dots." },
  "audienceStyle.nameRequired": { zh: "请输入标签名称。", en: "Tag name is required." },
  "audienceStyle.invalidKind": { zh: "类型必须是受众或风格。", en: "Type must be Audience or Style." },
  "audienceStyle.invalidLanguage": { zh: "内容语言必须是中文或英文。", en: "Content language must be Chinese or English." },
  "audienceStyle.invalidData": { zh: "标签数据无效，请检查字段或存储文件。", en: "Invalid tag data. Check the fields or stored file." },
  "audienceStyle.duplicateId": { zh: "此 ID 已存在，请使用其他 ID。", en: "This ID already exists. Use a different ID." },
  "audienceStyle.duplicateName": { zh: "同一内容语言下已有此名称。", en: "A tag with this name already exists in the same content language." },
  "audienceStyle.immutableId": { zh: "已保存标签的 ID 不可修改。", en: "The ID of a saved tag cannot change." },
  "audienceStyle.notFound": { zh: "标签不存在或已被删除。", en: "Tag not found or already deleted." },
  "audienceStyle.projectNotFound": { zh: "当前项目不存在，未能复制标签。", en: "The current project was not found. The tag could not be copied." },
  "audienceStyle.invalidProject": { zh: "项目配置无效，未能复制标签。", en: "Invalid project configuration. The tag could not be copied." },
  "audienceStyle.loadFailed": { zh: "加载标签失败，请重试。", en: "Failed to load tags. Please retry." },
  "audienceStyle.saveFailed": { zh: "保存标签失败，请重试。", en: "Failed to save the tag. Please retry." },
  "audienceStyle.deleteFailed": { zh: "删除标签失败，请重试。", en: "Failed to delete the tag. Please retry." },
  "audienceStyle.copyFailed": { zh: "复制标签失败，请重试。", en: "Failed to copy the tag. Please retry." },
} as const;
